# Generated by Django 3.2.16 on 2022-11-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps', models.CharField(max_length=255)),
                ('ecg', models.CharField(max_length=255)),
                ('temp', models.CharField(max_length=255)),
                ('humid', models.CharField(max_length=255)),
                ('gs', models.CharField(max_length=255)),
                ('bms', models.CharField(max_length=255)),
            ],
        ),
    ]
